### ISSUE TITLE
Name the Game!

### ISSUE THREAD

**Issue by retwedt** [sporadic-labs/octo-chainsaw#75]
Name the damn game!

[Random Name Generators](http://www.seventhsanctum.com/index.php)

**Comment by retwedt** [comment]
Possible Ideas:
 - The Heinous Case of The Molecular Mission
 - The Terrifying Secret of The Licentious Mary Taylor
 - The Diabolical Touch of Science
 - Cannibal Pilgrimage to The Hollow Earth
 - The Diabolical Adventures of the Dinosaur-Women
 - The Impossible Armored Person

**Comment by mikewesthad** [comment]
The confounding case of the molecular mission
The confounding case of the atomic mission
The astounding atomic adventure
The adamant atomic adventure
Atomic antics
The calamitous case of the atomic antics
The caustic case of the molecular mission
**The atomic incident**
